server:
  error:
    include-message: always
    include-binding-errors: always
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql:
    show-sql: true
